#COMEÇAR UM AUTO ESTUDO SOBRE TUDO QUE O PROFESSOR JÁ PASSOU EM PYTHON, VOU DEIXAR EM LETRA MAIUSCULA PARA QUE SEJA MAIS FACIL LER PORÉM OS COMANDOS
#VOU BOTAR MINUSCULO OU DE MANEIRA QUE A PRIMEIRA SEJA MAIUSCULA E O RESTO MAIUSCULA POIS INTERFERE NO CODIGO, CONFORME FOR FALANDO EU VOU DIGITANDO
#SE INFLUENCIA OU NÃO

#SOBRE: COMANDO print() -- SEMPRE MINUSCULO
print() #COMANDO PRINT NADA MAIS É DO QUE UM COMANDO DE SAIDA, OU SEJA, COMANDO DE SAIDA É O QUE VAI SER MOSTRADO PARA O USUARIO
# PARA USAR COMANDO PRINT BASTA DIGITAR print E ABRIR PARENTESES PARA O VALOR () PORÉM, VOCÊ PRECISA BOTAR CONTEUDO DENTRO DELE, VAMOS COMEÇAR COM UMA 
# str (TRADUZIDO DO INGLES: STRing = LINHA) QUE REPRESENTA LINHA DE TEXTO (str É UM TIPO DE DADO)
# PARA DIGITAR UM VALOR COMO CARACTERE (str) VOCÊ PRECISA SEMPRE QUE FOR MEXER COM VALORES str BOTAR ASPAS SIMPLES ' OU DUPLA " NO COMEÇO E FIM 
#DO TEXTO INSERIDO DENTRO DOS PARENTESES  COMO NO EXEMPLO ABAIXO:
print('Olá mundo')
print('Academia estudantil')
print("Fatec Ogari")
# COMO VIMOS STR COMO DADOS DE CARACTERES, AGORA VAMOS PARA OS VALORES QUE SÃO int (INTEGER = INTEIRO) QUE ACEITARA E CONSEGUIRA FAZER LEITURA
#DE NUMEROS INTEIROS, OU SEJA, QUE NÃO POSSUAM VIRGULAS, DESDE POSITIVOS A NEGATIVOS
print(1) #NUMEROS DO TIPO int OU float NÃO PRECISAM DE ASPAS PARA SEREM ENTENDIDOS, ASPAS SERÁ USADO *APENAS* EM STR, STR É O ÚNICO TIPO DE DADO
# Q PRECISA DE ASPAS
print(10)
print(100)
# TAMBÉM PODEMOS FAZER EXPRESSOES NÚMERICAS
print( 100+24*2 - 10) #ELE USARÁ A ORDEM MATEMATICA, OU SEJA, PRIMEIRO ELE FARÁ PARENTESES, SE NÃO TIVER ELE FARÁ POTENCIA OU RAIZ QUADRADA, SE NÃO
#TIVER NENHUM DOS ANTERIORES ELE VAI DAR PRIORIDADE EM FAZER PRIMEIRO MULTIPLICACAO E DIVISAO E POR PRIORIDADE MENOR SERA ADICAO E SUBTRACAO
print((100+24)*2-10)
print(100+(24*(2-10)))# PODEMOS TAMBÉM DAR PRIORIDADE DENTRO DE PRIORIDADES, NESSE EXEMPLO ELE FARÁ PRIMEIRO 2-10 QUE ESTÁ EM PRIORIDADE DE 2 PARANTESES
# E DEPOIS FARA 24 * RESULTADO DO PARENTESES DE MAIOR PRIORIDADE E DEPOIS O RESTO DA EQUACAO
#ENTAO EM ORDEM VAI EXECUTAR:
# 2 - 10 = -8
# 24 * -8 = -192
# 100 + (-192) = -92
#VAI MOSTRAR P USUARIO -92
# VALORES FLOAT SÃO DECIMAIS, PORÉM COMO LEVA EM BASE A LINGUAGEM AMERICANA, COMO STR = STRING E INT = INTEGER, TAMBÉM PEGA A REGRA DELES DE
# ACENTUACAO, E DIFERENTE DO NOSSO QUE PARA DECIMAIS SÃO VIRGULA, LA NA AMERICA DO NORTE É PONTO FINAL, ENTÃO AO INVÉS DE DIZER R$100,50 ELES 
# DIRIAM $100.50, ENTÃO QUANDO VOCÊ FOR DECLARAR VALORES FLOAT EM PYTHON, USE . AO INVÉS DE ,
print( 10.234) #ESSE NÚMERO É EQUIVALENTE A 10,234 NA REGRA DE ACENTUACAO NUMERICA BRASILEIRA
print(3.1415) #ESSE NÚMERO É EQUIVALENTE A 3,1415 NA REGRA DE ACENTUACAO NUMERICA BRASILEIRA
# PARA IMPRIMIR MAIS DE UM ELEMENTO EM PRINT A GENTE USA VIRGULA ( , ) PARA SEPARAR OS ELEMENTOS, ENTÃO POR EXEMPLO:
print('Fatec','Sp','Brasil') # USANDO VIRGULA ELE IMPRIMIRA AS PALAVRAS, E ISSO TAMBÉM SERVE PARA NÚMEROS E FLOAT:
print('Fatec',279,8.75)

#DECLARAÇÃO DE VARIAVEIS
#PARA DECLARAR VARIAVEIS VAMOS USAR O SINAL DE IGUAL ( = ) E DECLARAR O TIPO DE DADO QUE ELE É 
escola = str('EATIs')
nome = str('Alfredo')
idade = int(40) 
cidade = str('Itaipu')
pontuacao = float(7.75) # É BOM EVITAR ACENTOS EM VARIAVEIS, USE ACENTOS APENAS EM PRINT STR 
matriculado = bool(True) # BOOL É VALOR BOOLEANO QUE O PROFESSOR AINDA NÃO ENTROU MUITO EM DETALHE MAS SE REFERE PRATICAMENTE A 2 VALORES, BOOLEANO
#VAI RETORNAR SEMPRE VERDADEIRO OU FALSO, SÃO OS DOIS UNICOS VALORES PARA ELE, NESSE CASO EU DEFINI COMO ELE ESTAR MATRICULADO COMO VERDADEIRO
# E UM DETALHE É QUE True E False TEM QUE SER ESCRITO COMO PRIMEIRO MAIUSCULO E O RESTO MINUSCULO, EU NAO VOU ENTRAR EM DETALHE PORQUE ELE MESMO 
#NÃO PASSOU MUITO SOBRE ISSO, MAS ESTOU TE MOSTRANDO QUE EXISTE

#MOSTRANDO VARIAVEIS
#PARA MOSTRAR VARIAVEIS EM UM print() BASTA A GENTE SEPARAR POR VIRGULA E BOTAR O NOME DA VARIAVEL QUE NEM QUANDO VOCÊ PRINTA MAIS DE UM ITEM
print('Na escola',escola,', da cidade',cidade,', existe o professor chamado',nome,'que tem',idade,'anos e ficou com a média',pontuacao,'no vestibular realizado dia ...')
#AQUI ESTOU DECLARANDO COMO:
#EXIBA A STRING 'NA ESCOLA' , EXIBA CONTEUDO DA VARIAVEL ESCOLA , EXIBA A STRING 'DA CIDADE', EXIBA CONTEUDO DA VARIAVEL CIDADE , E POR ASSIM EM DIANTE
#EXISTE OUTRA FORMA QUE TAMBÉM É MAIS UTIL E TEM OUTRAS FUNCOES MAS NÃO VOU ENTRAR EM DETALHE QUE SE CHAMA F STRING QUE PRATICAMENTE É UM CODIGO
#QUE FAZ COM QUE VOCÊ NAO PRECISE USAR VIRGULAS PARA BOTAR VARIAVEIS E SIM {}, MAS O DE CIMA É O MAIS BASICO, VOU BOTAR EXEMPLO ABAIXO MAS SE 
#QUISER FAZER SO COM O DE CIMA VAI DAR CERTO TAMBÉM
#PARA FAZER F STRING VOCÊ VAI DECLARAR F NO COMEÇO DO PRINT SEGUIDO DE TODA PARTE DO CONTEUDO DENTRE ASPAS, VOU USAR O EXEMPLO ACIMA
print(f'Na escola {escola}, da cidade {cidade}, existe um professor chamado {nome} que tem {idade} anos e ficou com média {pontuacao} no vestibular realizado dia...')
#PERCEBE Q O F FICA AZUL, ELE PODE SER TANTO MINUSCULO COMO MAIUSCULO, É UNICA COISA QUE EU SEI Q DA P FAZER EM MAIUSCULA E MINUSCULA NO PYTHON
# OU SEJA, TODO[NÃO SEI PQ TÁ AZUL, SÓ RELEVA PQ IISSO É UM COMENTARIO DE QUALQUER JEITO Q NAO VAI ENTRAR NA LINHA DE EXECUÇÃO DO CÓDIGO]
# CONTEÚDO VAI FICAR DENTRO DOS PARENTESES, UM F ANTES DA STRING E AS VARIAVEIS VOCÊ PODE COLOCAR ELAS DENTRO DE CHAVES {}

#INPUT
#INPUT É UMA VARIAVEL QUE O USUARIO DIGITARÁ Q TERA UM VALOR E UM TIPO, É UMA ENTRADA DE DADOS, DIFERENTE DO PRINT QUE É SAIDA 
#PARA FAZER INPUT VOCÊ PRECISA SABER ANTES DE ALGUMA COISA: TODO INPUT PRECISA TER UMA VARIAVEL PARA QUE POSSA SER ARMAZENADO, ENTÃO UMA INPUT
#SEMPRE TERÁ QUE TER UMA VARIAVEL ALOCADA, E OUTRA COISA É QUE VOCÊ PRECISA DEFINIR O TIPO DE DADOS QUE O USUARIO PODERÁ DIGITAR, SENDO ELE ENTRE
# STR INT FLOAT E OS DEMAIS TIPOS DE DADOS, POR PADRAO SE VOCÊ SO COLOCAR INPUT E NÃO DECLARAR O TIPO DELE, ELE POR PADRAO VAI ATRIBUIR ESSE INPUT
# A UMA STR
# O INPUT É input() DENTRO DO PARENTESES VOCÊ PODE COLOCAR O TEXTO QUE SERA EXIBIDO PARA O USUARIO DURANTE O INPUT, COMO TEXTO JA VIMOS QUE É STR
# A GENTE PRECISA USAR AS ASPAS
variavel1 = input('Digite variavel 1: (nesse input o valor que você digitar será considerado uma STR, ou seja, você pode botar qualquer coisa aqui, numeros, decimais ou linhas de texto, ele vai reconhecer tudo como texto, então se você botar 20 por exemplo sera considerado 20 como texto e não como numero, então eventualmente você não podera usar ele para contas mas só para exibição ou comparação) DIGITE AQUI NA FRENTE ONDE TEM UM QUADRADO ESPERANDO SEU INPUT, SÓ CLICAR PARA APARECER --->')
Variavel1 = str(input('Aqui estou declarando que é str, mas de padrao já é assim então nao tem uma real necessidade, mas veja que a variavel que eu nomei é a mesma da de cima com apenas uma diferença, que a primeira letra V é maiuscula, isso já da a possibilidade de outra variavel, elas não sao as mesmas por uma unica diferenca de letra maiuscula e minuscula'))
variavel2 = int(input('Aqui tem dois parenteses, o primeiro referente ao int() que declaramos que o valor dentro do parenteses do int é do tipo inteiro que é o input, e o outro parenteses é o conteudo do input onde to escrevendo essa str, nesse tipo de dado ele apenas aceitara números inteiros positivos ou negativos, se você digitar algum caractere ou decimal na execucao dessa linha de input dará erro, você pode rodar o texto e ver por si mesmo'))
variavel3 = float(input('Aqui é a mesma coisa do int so que com decimais, aqui em float ele reconhece numeros inteiros e decimais, enquanto o int so inteiros, geralmente valores float são exibidos com pelo menos uma casa apos a virgula, mesmo que esse número seja inteiro'))
print(variavel1) # AQUI SERÁ EXIBIDO AS VARIAVEIS SE VOCÊ COLOCOU CORRETAMENTE NO CAMPO ACIMA
print(variavel2)
print(variavel3)
print(Variavel1)